title: Marino's Podcast Notes
description: Archive of notes and transcripts
url: 'https://marinolinic.github.io'
baseurl: '/podcasts'

permalink: /:title/
theme: null
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
